version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - kaddem_network

  backend:
    depends_on:
      - mysqldb
    image: alimaalej/kaddem-4twin2-g1-kaddem:latest
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddem_db?createDatabaseIfNotExist=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : null,
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    stdin_open: true
    tty: true
    networks:
      - kaddem_network

volumes:
  db:

networks:
  kaddem_network:
    driver: bridge
