version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kaddem_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - kaddem_network

  backend:
    depends_on:
      - mysqldb
    image: hamzabox/ayarihamza-g1-kaddem-api:latest
    # build: ./backend  # Uncomment if you want to build the backend locally
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddem_db?createDatabaseIfNotExist=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : null,
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    stdin_open: true
    tty: true
    networks:
      - kaddem_network
    container_name: kaddem-backend

  frontend:
    image: hamzabox/ayarihamza-g1-kaddem-frontend:latest
    container_name: kaddem-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - kaddem_network

volumes:
  db:

networks:
  kaddem_network:
    driver: bridge
